name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '22'

            - name: Set up AWS CLI
              uses: aws-actions/configure-aws-credentials@v3
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Create deploy.sh script
              run: |
                  echo '#!/bin/bash' > deploy.sh
                  echo 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533267071464.dkr.ecr.us-east-1.amazonaws.com' >> deploy.sh
                  echo 'docker buildx build --platform linux/amd64 -t 533267071464.dkr.ecr.us-east-1.amazonaws.com/atalanta-frontend:latest --push .' >> deploy.sh
                  chmod +x deploy.sh

            - name: Run deployment
              run: ./deploy.sh
